theme: jekyll-theme-tactile
#title: Dr. Sascha Wald's homepage
author: Dr. Sascha Wald
avatar: ./FCS1.png
round-avatar: true

social-network-links:
  email: "sascha.wald@coventry.ac.uk"
  facebook: deanattali
  github: saschawald
  ORCID: 0000-0003-1013-2130
  google-scholar: saschasebastianwald@gmail.com

